SET_CODES = {
	'1hp': 'History Pack 1',
	'arc': 'Arcane Rising',
	'bol': 'Boltyn Blitz Deck',
	'bri': 'Briar Blitz Deck',
	'bvo': 'Bravo, Showstopper Hero Deck',
	'chn': 'Chane Blitz Deck',
	'cru': 'Crucible of War',
	'dro': 'Dromai Blitz Deck',
	'ele': 'Tales of Aria',
	'evr': 'Everfest',
	'fab': 'Tournament Legal Special Use Promos',
	'fai': 'Fai Blitz Deck',
	'her': 'Hero Card Promos',
	'ira': 'Ira Welcome Deck',
	'jdg': 'Judge Unique Promos',
	'ksu': 'Katsu, the Wanderer Hero Deck',
	'lev': 'Levia Blitz Deck',
	'lgs': 'Local Game Store Promos',
	'lss': 'Non-Tournament Legal Special Use Promos',
	'lxi': 'Lexi Blitz Deck',
	'mon': 'Monarch',
	'old': 'Oldhim Blitz Deck',
	'oxo': 'Non-Tournament Legal Special Use Promos',
	'psm': 'Prism Blitz Deck',
	'rnr': 'Rhinar, Reckless Rampage Hero Deck',
	'tea': 'Dorinthea Ironsong Hero Deck',
	'upr': 'Uprising',
	'win': 'Worlds / Pro Tour Prize Cards',
	'wtr': 'Welcome to Rathe',
	'xxx': 'OP Event Tokens'
}